### ISSUE TITLE
error: ‘gflags’ has not been declared

### ISSUE THREAD

**Issue by waitwaitwaitforME** [AIBluefisher/EGSfM#2]
Hello! Thank you for your open source! And I have some problems when I built the EGSfM:
In function ‘int main(int, char**)’:
/home/**/EGSfM/ext/libvot/src/examples/image_search.cpp:61:2: **error: ‘gflags’ has not been declared**    gflags::ParseCommandLineFlags(&argc, &argv, true);

and
/home/**/EGSfM/app/fisher_vector_similarity.cpp:101:5: error: ‘gflags’ has not been declared
     gflags::ParseCommandLineFlags(&argc, &argv, false);
/home/**/EGSfM/app/fisher_vector_trainer.cpp:76:5: error: ‘gflags’ has not been declared
     gflags::ParseCommandLineFlags(&argc, &argv, false);

I have already installed the gflags and some paths are shown below.
GFLAGS_INCLUDE_DIR:PATH=/usr/include
GFLAGS_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libgflags.so
// gflags namespace (google or gflags)
GFLAGS_NAMESPACE:STRING=google

So could you please give me some advice on how to deal with this problem? Thank you so much!

**Comment by AIBluefisher** [comment]
Does the cmake find the path of `gflag`? Could you provide more information, as it's hard for me to reproduce this issue.

**Comment by waitwaitwaitforME** [comment]
Sorry to bother you. In cmake step, the corresponding messages are as follows.
-- Check for Google Log
-- Found Glog: /usr/local/include  
-- Found Google Logging: /usr/local/include
-- Check for gflags
-- Found GFlags: /usr/include
...
-- Found GFlags: /usr/local/include  
-- Found gflags  (include: /usr/local/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog (include: /usr/local/include, library: /usr/local/lib/libglog.so)
...
-- Found required Ceres dependency: gflags
No error occured in the cmake step.

**Comment by waitwaitwaitforME** [comment]
I have solved this problem. Thank you so much!
